const path = require("path");
const fs = require("fs");
const webpack = require("webpack");
const HtmlWebpackPlugin = require("html-webpack-plugin");
const CopyPlugin = require("copy-webpack-plugin");
// favicons-webpack-plugin drags in sharp (native binary download, often
// blocked); the favicon is cosmetic, so use it only when it's installed.
let FaviconsWebpackPlugin = null;
try { FaviconsWebpackPlugin = require("favicons-webpack-plugin"); } catch {}

module.exports = (env, argv) => {
  return {
    entry: "./src/index.js",
    output: {
      filename: "main.js",
      path: path.resolve(__dirname, "dist"),
    },
    devtool: "eval-cheap-source-map",
    devServer: {
      compress: true,
      port: 3001,
      proxy: {
        "/socket.io": {
          target: "http://localhost:3002",
          ws: true,
        },
      },
      headers: {
        "Access-Control-Allow-Origin": "*",
        "Cross-Origin-Embedder-Policy": "require-corp",
        "Cross-Origin-Opener-Policy": "same-origin",
      },
    },
    module: {
      rules: [
        {
          test: /\.tsx?$/,
          use: "ts-loader",
          exclude: /node_modules/,
        },
        {
          test: /\.css$/,
          use: ["style-loader", "css-loader"],
        },
        {
          test: /\.(png|otf)$/,
          type: "asset/resource",
        },
      ],
    },
    plugins: [
      new webpack.DefinePlugin({
        DEV_MODE: argv.mode == "development",
        // Serverless build (static hosting): bake the in-browser server in.
        OFFLINE_MODE: JSON.stringify(!!process.env.OFFLINE_MODE),
      }),
      ...(FaviconsWebpackPlugin ? [new FaviconsWebpackPlugin("./public/favicon.png")] : []),
      new HtmlWebpackPlugin({
        template: "./public/index.html",
        filename: "index.html",
        path: path.resolve(__dirname, "dist"),
      }),
      new webpack.ProvidePlugin({
        $: "jquery",
        jQuery: "jquery",
      }),
      new CopyPlugin({
        patterns: [
          { from: "./public/robots.txt", to: "robots.txt" },
          { from: "./public/coi-serviceworker.min.js", to: "coi-serviceworker.min.js" },
          { from: "./src/workers", to: "./src/workers" },
          { from: "./assets/textures", to: "./textures" },
          { from: "./assets/images", to: "./images" },
          { from: "./assets/audio", to: "./assets/audio" },
          // building.json (generated by scripts/setup_blockcraft.py) powers
          // the serverless build; skip quietly when it hasn't been generated.
          ...(fs.existsSync(path.resolve(__dirname, "public/building.json"))
            ? [{ from: "./public/building.json", to: "building.json" }]
            : []),
        ],
      }),
    ],
    resolve: {
      extensions: [".ts", ".js", ".json"],
    },
  };
};
